/// Flutter icons AppIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData tab_todo = const IconData(0xe613, fontFamily: _kFontFam);
  static const IconData tab_task = const IconData(0xe612, fontFamily: _kFontFam);
  static const IconData tab_job = const IconData(0xe611, fontFamily: _kFontFam);
  static const IconData tab_me = const IconData(0xe60f, fontFamily: _kFontFam);
}
